### ISSUE TITLE
Use RbConfig instead of obsolete and deprecated Config

### ISSUE THREAD

**Issue by emmx** [rubyconfig/config#148]
In jRuby (9.0.5.0 (2.2.3)) at least, the following error is thrown:

```
~/.rvm/gems/jruby-9.0.5.0/gems/config-1.2.1/lib/config/compatibility.rb:1:in `<top>':
Use RbConfig instead of obsolete and deprecated Config.
```

This is due to Config being used in [config/compatibility.rb](https://github.com/railsconfig/config/blob/master/lib/config/compatibility.rb#L1), line 1.

A workaround would be to use **Kernel.config_defined?** instead of **defined?**.

``` ruby
if Kernel.const_defined?(:RbConfig) && Kernel.const_defined?(:Config)
  Object.send :remove_const, :Config
end
```

**Comment by pkuczynski** [comment]
I believe this has been already fixed by moving from Kernel to Class. @emmx would you like to have another look on this?

**Comment by pkuczynski** [comment]
Closing due inactivity...
