### ISSUE TITLE
settings*yml and spring preload

### ISSUE THREAD

**Issue by fuminori-ido** [rubyconfig/config#165]
When I use railsconfig with rails5, "rails runner" doesn't have latest config/settings*yml values in development mode.

My workaround is to add settings*yml in config/spring.rb as follows:

```
%w(
  ...
  config/settings.local.yml
  config/settings.yml
  config/settings/
).each { |path| Spring.watch(path) }
```

Q1) Is this right way?
Q2) Spring is default bundled since rails 4.1, and if some additional configuration is required to use railsconfig with rails as above, could you mention the way to README.md ?

**Comment by pkuczynski** [comment]
@rdubya what you think?

**Comment by rdubya** [comment]
I don't use Spring so I don't really have any insight into this. I believe Rails 6 introduced a replacement for Spring so not sure if its worth dealing with at this point or not.

**Comment by pkuczynski** [comment]
@fuminori-ido this should not be needed as Config should plug itself into a proper rails run-up stage by default. If this is not the case could you prepare a repo with example app illustrating the issue?

**Comment by pkuczynski** [comment]
Closing due inactivity...
