### ISSUE TITLE
Disallow assignment

### ISSUE THREAD

**Issue by Fryguy** [rubyconfig/config#170]
I'm thinking it would be really useful if there was a way to configure Config::Options to not allow assignment or to raise an exception.  We've had cases where developers didn't realize the settings wouldn't persist, and did `Settings.the_setting = 42`, which happily works and moves on.  This is particularly painful in tests because then we would get test contamination across tests since the Settings are a singleton.

**Comment by pkuczynski** [comment]
@Fryguy I think we already solved it by moving to instance variables (instead of class variables). Can you check again?

**Comment by pkuczynski** [comment]
Closing due inactivity...
