### ISSUE TITLE
uninitialized constant Config (NameError)

### ISSUE THREAD

**Issue by ahcarpenter** [rubyconfig/config#192]
This is on boot with the generated initializer.

Running Ruby 2.4.1 and Rails 5.1.4

**Comment by pkuczynski** [comment]
@ahcarpenter is this still and issue for you?

**Comment by dipanm** [comment]
When you write a simple first line like

`Config.load_and_set_settings("/path/to/yaml1", "/path/to/yaml2", ...)` in 
my_app.ruby (even after Gemfile having it and bundle install done), you get this error right way...

So obviously this is not a bug - but we don't know how to use it. 

The documentation says 

> Add the gem to your Gemfile and run bundle install to install it. Then initialize Config manually within your configure block. 

Question is how? - We don't get a symbol Config. 
Also tried  `require 'config'` 
But it throws an error saying no such file.
How do you really use it? 
Do you have any example plain ruby code that uses this successfully?

**Comment by dipanm** [comment]
Okay - it does work for me. I think `bundle install` didn't work, but doing `gem install config` manually worked. Don't know why.

**Comment by Riveascore** [comment]
I'm having the same issue.

**Comment by cjlarose** [comment]
@Riveascore Feel free to open up a new issue. If you can, please include a complete reproducible test project. That'll greatly increase our ability to debug and address the issue.
