### ISSUE TITLE
Specs rely on test order

### ISSUE THREAD

**Issue by malakai97** [rubyconfig/config#198]
## Description

Running the specs in a random order results in multiple failed specs, depending on the order's seed.  

## Rubies 

* 2.3.4
* 2.4.2 - appraisal will not run the entire suite regardless of errors encountered

## Steps to Reproduce

1. git clone, etc
2. `bundle install`
3. `appraisal install`
4. add `--order random` to the `.rspec` file
5. `appraisal rspec`

### Seeds which are known to result in errors

* 19209 - Multiple KeyErrors
* 5710 - Expectation failures in config_env_spec
* 61592 - Exactly one failed test in setting the constant to use for settings

**Comment by pkuczynski** [comment]
If you willing to help, you are more then welcome! :)
