### ISSUE TITLE
no implicit conversion of Symbol into Integer when config.use_env = true 

### ISSUE THREAD

**Issue by DonGiulio** [rubyconfig/config#205]
Hello, 

I found this problem with a specific combination of ENV variables like: 

```
BACKEND_DATABASE=development
BACKEND_DATABASE_USER=postgres
```

When iterating on the second env variable [lib/config/options.rb](https://github.com/railsconfig/config/blob/master/lib/config/options.rb#L62) raises  `no implicit conversion of Symbol into Integer` when trying to find `leaf[keys.last]` but leaf is a string containing `development`. 

My workaround for this is to make sure the ENV variables don't get into this form of nesting. 

```
BACKEND_DATABASE_NAME=development
BACKEND_DATABASE_USER=postgres
```

It's probably reasonable to require this form in the docs, as I wouldn't imagine how to create a structure where one of the keys contains both data and other keys.

**Comment by pkuczynski** [comment]
@DonGiulio would you like to provide a PR with updated documentation?

**Comment by pkuczynski** [comment]
@cjlarose should we do anything about it?

**Comment by cjlarose** [comment]
I'll look into this. I think we can update the implementation to make the error condition more clear.

**Comment by cjlarose** [comment]
Updated the implementation to give a more descriptive error message and updated the docs in #293
