### ISSUE TITLE
Support hash loading

### ISSUE THREAD

**Issue by shahoxo** [rubyconfig/config#239]
Do you have any plans that `Config.load_files` support Hash or add `Config.load_hashes` ?

https://github.com/railsconfig/config/blob/2.0.0/lib/config/options.rb#L20
https://github.com/railsconfig/config/blob/2.0.0/lib/config.rb#L47

`Config::Options#add_source!` has been already supported Hash, but `Config.load_files` has not been supported Hash.

**Comment by pkuczynski** [comment]
Do you mean like adding support for loading config from JSON files? This could be done fairly easily I believe. Nobody requested it so far, but I can add it if you need it?

**Comment by shahoxo** [comment]
I'd like to load transformed yaml easily.
For example
```yaml
# UpperCamelCase.yml
Foo:
  Bar: 1
```
if load yaml normally
```ruby
Config.load_and_set_settings("/path/to/UpperCamelCase.yml")
Settings.Foo.Bar
#=> 1
```

if underscore access
```ruby
settings = YAML.load_file(file_path).deep_underscore_keys
#=> { foo: { bar: 1 } }
name = Config.const_name
Object.send(:remove_const, name) if Object.const_defined?(name)
opt = Config::Options.new
opt.add_source!(settings)
opt.load!
Object.const_set(name, opt)

Settings.foo.bar
#=> 1
```

Above definition is too long, so I'd expect following shorthand.
```ruby
settings = YAML.load_file(file_path).deep_underscore_keys
Config.load_and_set_settings(settings)
```

**Comment by pkuczynski** [comment]
Why do you need `deep_underscore_keys`?

**Comment by shahoxo** [comment]
I often want to import Yaml generated by other libraries as a config.
If the Yaml has a hard-to-use structure, the imported settings will also become a hard-to-use interface. 
(ex. Settings.Foo.bar. I'd like to access Settings.foo.bar)
`deep_underscore_keys` is a crude example for processing Yaml.

I am sorry that it is difficult to transmit in my poor English
i'd like to add following interface
```ruby
hash = {foo:: bar}
Config.load_hashes (hash)
# or
Config.load_and_set_settings (hash)
```

**Comment by pkuczynski** [comment]
Have you tried?

```
Settings.add_source!("/path/to/source.yml")
Settings.reload!
```

or following this example: https://github.com/railsconfig/config/issues/187#issuecomment-518938481

**Comment by pkuczynski** [comment]
Closing due inactivity...
