### ISSUE TITLE
Reload works only for one process

### ISSUE THREAD

**Issue by pioz** [rubyconfig/config#257]
In production, I call `Settings.reload!`, after saving the new config in `settings.yml`. The settings seem updated only in the current process, but not for all other Passenger processes. I need to `touch tmp/restart.txt` to be sure that the configuration is up to date on all processes.

Others have had this problem? Any idea to solve?

**Comment by pkuczynski** [comment]
Why would you modify `settings.yml` in production?

**Comment by pioz** [comment]
> Why would you modify `settings.yml` in production?

To modify `settings.yml` via admin interface. I don't know if it is a bad idea, but for some settings which are changed rarely could be interesting.

**Comment by pkuczynski** [comment]
Maybe you can try implementing something similar to the solution given here: https://stackoverflow.com/questions/48506247/rails-reload-dynamic-routes-on-multiple-instances-servers/48889163#48889163

**Comment by pkuczynski** [comment]
Closing due inactivity
