### ISSUE TITLE
AWS secrets manager?

### ISSUE THREAD

**Issue by hopewise** [rubyconfig/config#271]
Currently we use Capistrano to deploy our app to AWS, which we can handle to symlink `config/settings/production.yml`, however, we are studying the possibility of using AWS [Fargate](https://aws.amazon.com/fargate/),  and it seems that AWS [Secrets Manager](https://aws.amazon.com/secrets-manager/) is recommended when using Fargate.

Not to mention that maximum secret size for AWS Secrets Manager in 10kb, while our `production.yml` size is about 50kb, I will have to re-fill it in multiple secrets .. there must be work around for this..

The question is, what's the possibilities to use AWS Secrets Manager to populate the settings behind the scenes rather than relying on files at for ex: `config/settings/production.yml` ? so that we keep our code not changed, ex: `Settings.stripe.publishable_key` ?

**Comment by pkuczynski** [comment]
I think the easiest option would be to expose secrets from AWS Secrets Manager to Config using environment variables. Have a look at https://github.com/rubyconfig/config#working-with-environment-variables to see how to automatically populate ENV into settings

**Comment by pkuczynski** [comment]
And if you find something which is not mentioned in the documentation, please share it with the community via pull request to README :)

**Comment by hopewise** [comment]
Thanks, considering aws pricing $0.4 per a secret, its too expensive comparing to the number of secrets we have! I must find a solution, like grouping each 100 secret or so in one secret.. or completely drop the aws secrets manager idea..

**Comment by cjlarose** [comment]
A fix for this was implemented in #299 and released in config version 3.0.0.
