### ISSUE TITLE
The file `settings.local.yml` is loaded when running rspec tests

### ISSUE THREAD

**Issue by khiav223577** [rubyconfig/config#273]
There is a note in README says:
> NOTE: The file settings.local.yml will not be loaded in tests to prevent local configuration from causing flaky or non-deterministic tests. 

But it seems that the setting in `config\settings.local.yml` is loaded. And it will overwrite the setting in `config\settings\test.yml`.

### Environments
- Rails 5.2.4
- ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- config (2.0.0)

**Comment by pkuczynski** [comment]
This line should exclude `local` when running in test env:

https://github.com/rubyconfig/config/blob/master/lib/config.rb#L67

This assumes your env is properly set to `test`. Can you check that?

**Comment by khiav223577** [comment]
> This assumes your env is properly set to `test`. Can you check that?

The env is `test`. See:

![image](https://user-images.githubusercontent.com/4011729/77583582-4f64e080-6f1c-11ea-80b8-602e84edcda6.png)

**Comment by khiav223577** [comment]
I found out it was fixed in https://github.com/rubyconfig/config/pull/233

The issue is solved by upgrading `config` from 2.0.0 to 2.2.1 :)

**Comment by pkuczynski** [comment]
I should have asked if you are using the latest version :)
