### ISSUE TITLE
Ways to reload config of a running process?

### ISSUE THREAD

**Issue by vassilevsky** [rubyconfig/config#300]
Hello :)

Can I send a signal to the process that will make Config reload the configuration?

Will it reload a configuration file after it changes?

Any other way to trigger a reload without restarting the process?

Thanks!

**Comment by cjlarose** [comment]
> Can I send a signal to the process that will make Config reload the configuration?

It's possible to reload settings (even settings specified in YAML files) at runtime by executing [`Settings.reload!`](https://github.com/rubyconfig/config/blob/2748274b187aa86e71d8b88951a9ab57d7f988d0/README.md#reloading-settings)

The config gem doesn't automatically register any signal handlers to do this, but such a mechanism can be added to your application:

```ruby
  Signal.trap("HUP") do
    Settings.reload!
  end
```

> Will it reload a configuration file after it changes?

The config gem does not listen to file change events and automatically reload, but it's possible to implement something like that in your application using something like the [`listen` gem](https://github.com/guard/listen), as long as you call `Settings.reload!` in response to changes to the file.

> Any other way to trigger a reload without restarting the process?

A more native solution that's often useful in development environments is to just call `Settings.reload!` at the beginning of every web request, assuming your application is a web server. When used with Rails, the config gem does this automatically.
