### ISSUE TITLE
avoid Hash monkey patch when loading DeepMerge

### ISSUE THREAD

**Issue by davidgoldelocks** [rubyconfig/config#314]
followup to #120

`DeepMerge` can be loaded in 3 different ways:
1. only the `core` library
2. the `core` library + the default `Hash` monkey patch
3. the `core` library + an alternative `Hash` monkey patch that does not conflict with `ActiveSupport`

`Config` is currently using the [2nd variant](https://github.com/danielsdeleo/deep_merge/blob/master/lib/deep_merge.rb):
https://github.com/rubyconfig/config/blob/9c35a5d579e548b2c439cd4defb247baf51dbb64/lib/config.rb#L9

However, `Config` does not actually use the monkey patch, so it should switch to the 1st variant:
```ruby
require 'deep_merge/core'
```

This is conceptually cleaner and prevents the conflict with `ActiveSupport`.

**Comment by davidgoldelocks** [comment]
If end users want either of the monkey patches, they can require them directly:
```ruby
require 'deep_merge/deep_merge_hash'
```
```ruby
require 'deep_merge/rails_compat'
```

**Comment by cjlarose** [comment]
I'm on to a PR with this change. I'll likely bump the major version, though, since it's possible someone is implicitly depending on the `Hash` monkey patch in their application.
