### ISSUE TITLE
Help with beef please

### ISSUE THREAD

**Issue by Bengithebully** [rubyconfig/config#327]
Help please I am new to this I am trying to install BeEF on Mac in terminal I’ve done a lot and long story short when I was trying to change the credentials I messed up on the config_yaml tried to fix it and deleted tried to start at step one and now I’m running into a problem with ruby error 1.7.2 I believe # #

**Comment by pkuczynski** [comment]
I don't know whats BeEF? I guess you would need to ask them for help...
