### ISSUE TITLE
Released Version 4.1.0 still uses removed method `File.exists?`

### ISSUE THREAD

**Issue by the-teacher** [rubyconfig/config#328]
`ruby 3.2.0 (2022-12-25 revision a528908271) [aarch64-linux]`

```rb
/usr/local/bundle/gems/config-4.1.0/lib/generators/config/install_generator.rb:21:in
`modify_gitignore': undefined method `exists?' for File:Class (NoMethodError)

create_file '.gitignore' unless File.exists? '.gitignore'
```

Installing via github solves the problem.

```rb
gem 'config', "4.1.0", github: 'rubyconfig/config'
```
Please release a new version of the code. Thank you!

**Comment by jcoyne** [comment]
@cjlarose I'm wondering if you saw this issue?  Is there any chance a new release can be made? Thank you ❤️

**Comment by 9mm** [comment]
+1

**Comment by Uaitt** [comment]
It's may 3rd and the gem currently can't still be used because of `File.exists?` in the generator, which has been removed from ruby 3.2.0 😢 .

I'm wondering if there is a way to contact the maintainers in order to update the gem?

**Comment by jcoyne** [comment]
@cjlarose Thank you so much! ❤️

**Comment by cjlarose** [comment]
Thanks everyone for the pings. It's not always easy to dedicate time to this project, but the bumps on the issue really do help make clear when something is really broken for people. ❤️
