### ISSUE TITLE
minimum, maximum keys are conflicted with active_support methods.

### ISSUE THREAD

**Issue by ngoctien1102** [rubyconfig/config#329]
When upgrading my project to new version of Ruby and Rails, the settings stored with `minimum` and `maximum` keys are now raising errors:
`~/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/core_ext/enumerable.rb:44:in `minimum': wrong number of arguments (given 0, expected 1) (ArgumentError)`

Ruby version: 3.1.3
Rails version: 7.0.4.2

How to reproduce: 
- Initialize new rails project 
- Add gem config, then run bundle
- Edit `config/settings.yml` with:
![Screen Shot 2023-02-08 at 22 14 50](https://user-images.githubusercontent.com/37165184/217570600-3d90254f-e30f-4a09-a463-d2aeb4a6a0f7.png)
- In `rails console`, try access the value with `Settings.user_limit.minimum` and `Settings.user_limit.maximum`

Expect: Should be able to access minimum and maximum with corresponding values of 9 and 99
Reality: Error raises `~/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/core_ext/enumerable.rb:44:in `minimum': wrong number of arguments (given 0, expected 1) (ArgumentError)`

**Comment by ikael21** [comment]
Hi! I have the same issue after updating rails to 7 version. Is this issue fixed after all?

**Comment by pkuczynski** [comment]
Possibly this is related to https://github.com/rails/rails/issues/49457. We should have a fix soon...

**Comment by ikael21** [comment]
converting to hash working fine, but it's a temporary solution, waiting for the fix, thanks @pkuczynski 
```ruby
Settings.length.to_h[:maximum]
```

**Comment by rubywarlock** [comment]
Patch in https://github.com/rubyconfig/config/pull/342
doesn't fix it for me.

**Comment by pkuczynski** [comment]
I am not able to work on a fix, but I will happily approve a PR and make a quick release. Any volunteer?

**Comment by ikael21** [comment]
@pkuczynski  hi! I'd like to contribute. First, I need to explore a little bit how the code works and then I can suggest my solution and we can discuss it here

**Comment by ikael21** [comment]
@pkuczynski [pull request](https://github.com/rubyconfig/config/pull/347) is ready for review, I decided to fix it right away as it turned out to be an easy one 😸

**Comment by pkuczynski** [comment]
Merged and published! Thank you @ikael21
