### ISSUE TITLE
Extend Rails integration to application

### ISSUE THREAD

**Issue by retsef** [rubyconfig/config#330]
Thanks for your gem, it helps us a lot!

In our projects we use this gem to decompose some attributes, non necessary to be protected, outside of Rails credentials.
This helps our flow of PR reviews to be simpler and helps reads.

One of our usage has shown that it can be a duality with `Rails.application.credentials` values access with some sort of `Rails.application.settings` value access.

To be fair is not so different from use the class defined by `Config.const_name` directly but I think it can be also useful to have at the Rails application level

**Comment by rdubya** [comment]
I'm not against adding something like this, but I think it needs to be more configurable if we are going to do it by default. `settings` is a pretty common term that may cause conflicts in some environments. Using the constant is shorter and doesn't make it look like it is a part of the Rails implementation, so I think I'm more on the side of it just being something people do themselves. Any thoughts @pkuczynski ?

**Comment by retsef** [comment]
Thanks @rdubya for your response, and I also come up to not make this mandatory behavior in naming and pattern.
Rails has already [config_for](https://apidock.com/rails/Rails/Application/config_for) to have multiple settings file inside config folder. 

I will close this

**Comment by pkuczynski** [comment]
I agree @rdubya...
