### ISSUE TITLE
Environment variables not loaded anymore after upgrading to Rails 6.1.7.3

### ISSUE THREAD

**Issue by pippokairos** [rubyconfig/config#332]
### Description
We've been using the gem effectively up until Rails `6.1.7.2`, but after upgrading Rails to version `6.1.7.3` and config to `4.1.0` the environment variables are not available anymore in the `Settings`.

### Steps to reproduce
- Set the ENV usage to true and configure the other parameters
```
Config.setup do |config|
  config.const_name = 'Settings'

  config.fail_on_missing = true

  config.use_env = true
  config.env_prefix = 'SETTINGS'
  config.env_separator = '__'
  config.env_converter = :downcase
  config.env_parse_values = false
end
```
- Define an environment variable `SETTINGS__TEST__VAR=1`
- Run the Rails application on version `6.1.7.2` and config on version `2.2.3`
  - `Settings.test.var` is defined
- Run the Rails application on version `6.1.7.3` and config on version `4.1.0`
  - `Settings.test.var` is **NOT** defined

**Comment by pkuczynski** [comment]
Is this issue still valid?
