### ISSUE TITLE
How to use/mock in rspec?

### ISSUE THREAD

**Issue by slhck** [rubyconfig/config#336]
I would like to mock some settings temporarily for some Rspec tests.

How would I go about doing this?

When I do, inside a test:

```ruby
it "tests something" do
    Settings.add_source!(
        {
          foo: {
            bar: {
              baz: false
            }
          }
        }
      )
    Settings.reload!
end
```

This bleeds over to other tests rather than being local to a certain test.

I can do `Settings.reload_from_files` without any argument to clear all settings, but I'd rather not want to manually specify the default filenames for the various environments.

**Comment by cjlarose** [comment]
I'd suggest trying to use [`stub_const`](https://rspec.info/documentation/3.12/rspec-mocks/RSpec/Mocks/ExampleMethods.html#stub_const-instance_method) to replace the `Settings` constant with a [test double](https://rspec.info/documentation/3.12/rspec-mocks/RSpec/Mocks/ExampleMethods.html#double-instance_method).

See also [Constant Stubbing in RSpec 2.11](https://rspec.info/blog/2012/06/constant-stubbing-in-rspec-2-11/)

**Comment by jcoyne** [comment]
I do this in rspec:
```
before do
   allow(Settings.item).to receive(:sub_property).and_return('7')
end
```

**Comment by deepakmahakale** [comment]
Minitest

```ruby
# Settings.some_boolean
Settings.stub :some_boolean, true do
  # method_call
end

# Settings.app.some_boolean
Settings.app.stub :some_boolean, true do
  # method_call
end
```
