### ISSUE TITLE
Multi-environment settings not loading properly

### ISSUE THREAD

**Issue by aar0nr** [rubyconfig/config#78]
In `config/settings.yml`:

`foo: bar`

In `config/settings/development.yml`:

`foo: bar_dev`

In `config/settings/test.yml`:

`foo: bar_test`

When i start the rails console in the development environment, i.e. `rails console`, everything works as expected.  The value of `Settings.foo` equals `bar_dev`.

However, if I start the rails console in the test environment, i.e. `rails console -e test`, the value of `Settings.foo` still equals `bar_dev`.  I would expect it to equal `bar_test`.

I even tried `Settings.reload!`, but the value remains `bar_dev` when in the test environment.

Is this not working as expected, or am I missing something?

**Comment by pkuczynski** [comment]
I can not reproduce this issue. Please check https://github.com/railsconfig/config-rails-4.2 which implements example provided by you without any issues...

**Comment by pkuczynski** [comment]
Closing due inactivity...
